### ISSUE TITLE
Make sure to ask for latest version when pulling mongo

### ISSUE THREAD

**Issue by tordbb** [acntech/fruit-classifier#41]
When calling 
docker-compose up -d
in a terminal, it complaints something about a non-existing host.

In fruit-classifier - docker - docker-compose.yml, the file starts with:

```
version: '3'
services:

  mongo:
    image: mongo
    ports:
```

Make sure to replace this with 

```
version: '3'
services:

  mongo:
    image: mongo:latest
    ports:
```
